name: Bug report
description: Report a bug with the UCSC 2022 theme
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report! If this is an issue with one of UCSC's custom blocks (campus directory, course schedule, etc.), report it here: https://github.com/ucsc/ucsc-gutenberg-blocks
    - type: textarea
      attributes:
          label: Description
          description: Please write a brief description of the bug, including what you expect to happen and what is currently happening.
          placeholder: |
              Feature '...' is not working properly. I expect '...' to happen, but '...' happens instead
      validations:
          required: true

    - type: textarea
      attributes:
          label: Step-by-step reproduction instructions
          description: If possible, please write the steps needed to reproduce the bug.
          placeholder: |
              1. Add '...' to a page
              2. Confgure '...' settings
      validations:
          required: false

    - type: textarea
      attributes:
          label: Screenshots, screen recording, code snippet
          description: |
              If possible, please upload a screenshot or screen recording which demonstrates the bug. You can use LIEcap to create a GIF screen recording: https://www.cockos.com/licecap/
              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      validations:
          required: false

    - type: textarea
      attributes:
          label: Environment info
          description: |
              If possible, please indicate where your site is located and a URL where we can see an example of this bug.
          placeholder: |
              - Your site URL or a link to an example page.
              - Browser(s) are you seeing the problem on.
              - Device you are using and operating system (e.g. "Desktop with Windows 10", "iPhone with iOS 14", etc.).
      validations:
          required: true

    - type: dropdown
      id: existing
      attributes:
          label: Please confirm that you have searched existing issues in the repo.
          description: You can do this by searching https://github.com/ucsc/ucsc-2022/issues and making sure the bug is not already documented in another issue.
          multiple: true
          options:
              - 'Yes'
              - 'No'
      validations:
          required: true
