name: Reusable Workflow - Deploy Dokku
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
        description: Dokku Original App Name
      theme_folder:
        required: true
        type: string
        description: Dokku Theme Path

      branch:
        required: true
        type: string
        description: Branch to be deployed
      is_review_app:
        default: false
        required: false
        type: boolean
        description: Flag if this is a review app or not
      pr_number:
        required: false
        type: string
        description: Pull Request Number
      server:
        required: true
        type: string
        description: Server to deploy
    secrets:
      github_pat_token:
        required: true
      ssh_private_key:
        required: true
      slack_webhook:
        required: true

jobs:
  deploy_dokku:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: Extract branch name
        id: vars
        run: echo ::set-output name=branch::${GITHUB_REF#refs/*/}

      - name: Set common variables
        uses: moderntribe/actions/utils/common-variables@v1
        with:
          app_name: ${{ inputs.app_name }}
          base_branch: ${{ inputs.branch }}
          pr_number: ${{ inputs.pr_number }}

      - name: Setup SSH
        uses: moderntribe/actions/utils/ssh-agent@v1
        with:
          ssh_private_key: ${{ secrets.ssh_private_key }}
          server: ${{ inputs.server }}

      - name: Composer
        uses: moderntribe/actions/square1/composer@v1

      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version-file: ./.nvmrc

      - name: NPM Install
        run: npm install

      - name: NPM Build
        run: npm run build

      - name: Prepare deploy
        run: |
          mkdir -p ${{ inputs.theme_folder }}
          cp -r $(ls -A | grep -vE ".deploy|.git|node_modules") ${{ inputs.theme_folder }}

      - name: Install Theme composer
        working-directory: ${{ inputs.theme_folder }}
        run: |
          composer install --optimize-autoloader --ignore-platform-reqs --no-dev

      - name: Commit Files
        env:
          HUSKY: "0"
        uses: moderntribe/actions/utils/commit-files@v1
        with:
          folder: .deploy

      - name: Define app to deploy
        id: define_app
        run: |
          if [[ ${{ inputs.is_review_app }} == "true" ]]; then
            echo ::set-output name=deploy_app::${{ env.REVIEW_APP }}
          else
            echo ::set-output name=deploy_app::${{ inputs.app_name }}
          fi

      - name: Deploy to ${{ steps.define_app.outputs.deploy_app }}
        uses: moderntribe/actions/deploy/gitdeploy@v1
        with:
          git_url: "dokku@${{ inputs.server }}:${{ steps.define_app.outputs.deploy_app }}"
          branch: ${{ env.BRANCH }}
          folder: .deploy

      - name: Slack Notification
        if: success() || failure() || cancelled()
        uses: moderntribe/actions/utils/slack-message-deploy@v1
        with:
          branch: ${{ env.BRANCH }}
          environment: ${{ env.APPNAME }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          app_url: "${{ env.APPNAME }}.${{ secrets.server }}"
          gha_url: ${{ env.GHA_URL }}
          status: ${{ job.status }}

